name: Train Wine Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  train:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3
        pip install sagemaker==2.224.0
        pip install mlflow
        pip install pandas
        pip install scikit-learn
        pip install xgboost
        
    - name: Upload dataset to S3
      run: |
        aws s3 cp data/wine.csv s3://${{ secrets.S3_BUCKET }}/data/wine.csv
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Run pipeline
      run: python scripts/create_pipeline.py
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        SAGEMAKER_ROLE_ARN: ${{ secrets.SAGEMAKER_ROLE_ARN }}
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
